// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/admin" | "/admin/products" | "/admin/products/new" | "/admin/reviews" | "/admin/taxonomy" | "/analyser" | "/analyzed/[slug]" | "/analyzer" | "/app" | "/auth/error" | "/auth/login" | "/blog" | "/blog/[slug]" | "/brands" | "/brands/[brand]" | "/brands/[brand]/[product]" | "/certification" | "/certified" | "/consumers" | "/contact" | "/courses" | "/courses/skincare-101" | "/courses/skincare-101/welcome-9x4k2mq7" | "/disclaimer" | "/for-brands" | "/ingredients" | "/ingredients/[slug]" | "/learn" | "/learn/guides/[slug]" | "/learn/guides/[slug]/print" | "/methodology" | "/pitch" | "/preview/brand-certification-tcs2026-r8k2m5" | "/privacy-policy" | "/product/[id]" | "/review" | "/reviews/[slug]" | "/routine" | "/services" | "/shop" | "/standard" | "/standard/claims" | "/standard/register" | "/terms-of-use" | "/verified" | "/verify/codeskin-ultralite-certified-8f3t2p9x" | "/verify/codeskin-ultralite-evidence-r4t8w2k6" | "/verify/codeskin-ultralite-full-v2-p5r7k2" | "/verify/codeskin-ultralite-proof-q3w5e7r2" | "/verify/tcs-in-2026-048291-b7f2a9c1e5d3"
type AppRouteHandlerRoutes = "/api/admin/seed" | "/api/admin/set-admin" | "/api/analyze" | "/api/chat" | "/api/claim-check" | "/api/leads" | "/api/product-requests" | "/api/review" | "/api/reviews" | "/api/reviews/export" | "/api/scrape" | "/api/subscribe" | "/api/verified-products" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/analyzer" | "/preview/brand-certification-tcs2026-r8k2m5" | "/review"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/admin": {}
  "/admin/products": {}
  "/admin/products/new": {}
  "/admin/reviews": {}
  "/admin/taxonomy": {}
  "/analyser": {}
  "/analyzed/[slug]": { "slug": string; }
  "/analyzer": {}
  "/api/admin/seed": {}
  "/api/admin/set-admin": {}
  "/api/analyze": {}
  "/api/chat": {}
  "/api/claim-check": {}
  "/api/leads": {}
  "/api/product-requests": {}
  "/api/review": {}
  "/api/reviews": {}
  "/api/reviews/export": {}
  "/api/scrape": {}
  "/api/subscribe": {}
  "/api/verified-products": {}
  "/app": {}
  "/auth/callback": {}
  "/auth/error": {}
  "/auth/login": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/brands": {}
  "/brands/[brand]": { "brand": string; }
  "/brands/[brand]/[product]": { "brand": string; "product": string; }
  "/certification": {}
  "/certified": {}
  "/consumers": {}
  "/contact": {}
  "/courses": {}
  "/courses/skincare-101": {}
  "/courses/skincare-101/welcome-9x4k2mq7": {}
  "/disclaimer": {}
  "/for-brands": {}
  "/ingredients": {}
  "/ingredients/[slug]": { "slug": string; }
  "/learn": {}
  "/learn/guides/[slug]": { "slug": string; }
  "/learn/guides/[slug]/print": { "slug": string; }
  "/methodology": {}
  "/pitch": {}
  "/preview/brand-certification-tcs2026-r8k2m5": {}
  "/privacy-policy": {}
  "/product/[id]": { "id": string; }
  "/review": {}
  "/reviews/[slug]": { "slug": string; }
  "/routine": {}
  "/services": {}
  "/shop": {}
  "/standard": {}
  "/standard/claims": {}
  "/standard/register": {}
  "/terms-of-use": {}
  "/verified": {}
  "/verify/codeskin-ultralite-certified-8f3t2p9x": {}
  "/verify/codeskin-ultralite-evidence-r4t8w2k6": {}
  "/verify/codeskin-ultralite-full-v2-p5r7k2": {}
  "/verify/codeskin-ultralite-proof-q3w5e7r2": {}
  "/verify/tcs-in-2026-048291-b7f2a9c1e5d3": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/analyzer": never
  "/preview/brand-certification-tcs2026-r8k2m5": never
  "/review": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
