// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/products/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/products/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/taxonomy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/taxonomy">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/taxonomy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/analyser/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analyser">> = Specific
  const handler = {} as typeof import("../../../src/app/analyser/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/analyzed/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analyzed/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/analyzed/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/analyzer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analyzer">> = Specific
  const handler = {} as typeof import("../../../src/app/analyzer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../src/app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/error">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brands/[brand]/[product]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands/[brand]/[product]">> = Specific
  const handler = {} as typeof import("../../../src/app/brands/[brand]/[product]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brands/[brand]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands/[brand]">> = Specific
  const handler = {} as typeof import("../../../src/app/brands/[brand]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands">> = Specific
  const handler = {} as typeof import("../../../src/app/brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/certification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/certification">> = Specific
  const handler = {} as typeof import("../../../src/app/certification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/certified/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/certified">> = Specific
  const handler = {} as typeof import("../../../src/app/certified/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/consumers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consumers">> = Specific
  const handler = {} as typeof import("../../../src/app/consumers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses">> = Specific
  const handler = {} as typeof import("../../../src/app/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/courses/skincare-101/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses/skincare-101">> = Specific
  const handler = {} as typeof import("../../../src/app/courses/skincare-101/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/courses/skincare-101/welcome-9x4k2mq7/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses/skincare-101/welcome-9x4k2mq7">> = Specific
  const handler = {} as typeof import("../../../src/app/courses/skincare-101/welcome-9x4k2mq7/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/disclaimer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/disclaimer">> = Specific
  const handler = {} as typeof import("../../../src/app/disclaimer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/for-brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/for-brands">> = Specific
  const handler = {} as typeof import("../../../src/app/for-brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/ingredients/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ingredients/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/ingredients/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/ingredients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ingredients">> = Specific
  const handler = {} as typeof import("../../../src/app/ingredients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/learn/guides/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/guides/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/learn/guides/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/learn/guides/[slug]/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/guides/[slug]/print">> = Specific
  const handler = {} as typeof import("../../../src/app/learn/guides/[slug]/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/learn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn">> = Specific
  const handler = {} as typeof import("../../../src/app/learn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/methodology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/methodology">> = Specific
  const handler = {} as typeof import("../../../src/app/methodology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pitch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pitch">> = Specific
  const handler = {} as typeof import("../../../src/app/pitch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/preview/brand-certification-tcs2026-r8k2m5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview/brand-certification-tcs2026-r8k2m5">> = Specific
  const handler = {} as typeof import("../../../src/app/preview/brand-certification-tcs2026-r8k2m5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/product/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/product/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/review">> = Specific
  const handler = {} as typeof import("../../../src/app/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/reviews/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/reviews/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/routine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/routine">> = Specific
  const handler = {} as typeof import("../../../src/app/routine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../../src/app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop">> = Specific
  const handler = {} as typeof import("../../../src/app/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/standard/claims/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/standard/claims">> = Specific
  const handler = {} as typeof import("../../../src/app/standard/claims/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/standard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/standard">> = Specific
  const handler = {} as typeof import("../../../src/app/standard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/standard/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/standard/register">> = Specific
  const handler = {} as typeof import("../../../src/app/standard/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms-of-use/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-use">> = Specific
  const handler = {} as typeof import("../../../src/app/terms-of-use/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/verified/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verified">> = Specific
  const handler = {} as typeof import("../../../src/app/verified/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/verify/codeskin-ultralite-certified-8f3t2p9x/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify/codeskin-ultralite-certified-8f3t2p9x">> = Specific
  const handler = {} as typeof import("../../../src/app/verify/codeskin-ultralite-certified-8f3t2p9x/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/verify/codeskin-ultralite-evidence-r4t8w2k6/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify/codeskin-ultralite-evidence-r4t8w2k6">> = Specific
  const handler = {} as typeof import("../../../src/app/verify/codeskin-ultralite-evidence-r4t8w2k6/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/verify/codeskin-ultralite-full-v2-p5r7k2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify/codeskin-ultralite-full-v2-p5r7k2">> = Specific
  const handler = {} as typeof import("../../../src/app/verify/codeskin-ultralite-full-v2-p5r7k2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/verify/codeskin-ultralite-proof-q3w5e7r2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify/codeskin-ultralite-proof-q3w5e7r2">> = Specific
  const handler = {} as typeof import("../../../src/app/verify/codeskin-ultralite-proof-q3w5e7r2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/verify/tcs-in-2026-048291-b7f2a9c1e5d3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify/tcs-in-2026-048291-b7f2a9c1e5d3">> = Specific
  const handler = {} as typeof import("../../../src/app/verify/tcs-in-2026-048291-b7f2a9c1e5d3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/seed">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/set-admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/set-admin">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/set-admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze">> = Specific
  const handler = {} as typeof import("../../../src/app/api/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/claim-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/claim-check">> = Specific
  const handler = {} as typeof import("../../../src/app/api/claim-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/product-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/product-requests">> = Specific
  const handler = {} as typeof import("../../../src/app/api/product-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review">> = Specific
  const handler = {} as typeof import("../../../src/app/api/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reviews/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reviews/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/scrape/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scrape">> = Specific
  const handler = {} as typeof import("../../../src/app/api/scrape/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribe">> = Specific
  const handler = {} as typeof import("../../../src/app/api/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/verified-products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verified-products">> = Specific
  const handler = {} as typeof import("../../../src/app/api/verified-products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/analyzer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/analyzer">> = Specific
  const handler = {} as typeof import("../../../src/app/analyzer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/preview/brand-certification-tcs2026-r8k2m5/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/preview/brand-certification-tcs2026-r8k2m5">> = Specific
  const handler = {} as typeof import("../../../src/app/preview/brand-certification-tcs2026-r8k2m5/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/review/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/review">> = Specific
  const handler = {} as typeof import("../../../src/app/review/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
