// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/analyser" | "/analyzer" | "/app" | "/blog" | "/blog/[slug]" | "/brands" | "/certification" | "/certified" | "/consumers" | "/contact" | "/courses" | "/courses/skincare-101" | "/courses/skincare-101/welcome-9x4k2mq7" | "/disclaimer" | "/for-brands" | "/ingredients" | "/learn" | "/learn/guides/[slug]" | "/learn/guides/[slug]/print" | "/methodology" | "/privacy-policy" | "/product/[id]" | "/shop" | "/terms-of-use"
type AppRouteHandlerRoutes = "/api/analyze" | "/api/chat" | "/api/claim-check" | "/api/leads" | "/api/scrape"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/analyser": {}
  "/analyzer": {}
  "/api/analyze": {}
  "/api/chat": {}
  "/api/claim-check": {}
  "/api/leads": {}
  "/api/scrape": {}
  "/app": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/brands": {}
  "/certification": {}
  "/certified": {}
  "/consumers": {}
  "/contact": {}
  "/courses": {}
  "/courses/skincare-101": {}
  "/courses/skincare-101/welcome-9x4k2mq7": {}
  "/disclaimer": {}
  "/for-brands": {}
  "/ingredients": {}
  "/learn": {}
  "/learn/guides/[slug]": { "slug": string; }
  "/learn/guides/[slug]/print": { "slug": string; }
  "/methodology": {}
  "/privacy-policy": {}
  "/product/[id]": { "id": string; }
  "/shop": {}
  "/terms-of-use": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
