/**
 * Dove brand data
 *
 * Ingredient list sourced from incidecoder.com (verified June 2026).
 * Dove is a Unilever brand with global distribution, sold extensively in India.
 * The Body Love range is positioned around skin barrier science and body positivity.
 */

import type { Brand, ProductScorecard } from "./types";

const BRAND_SLUG = "dove";
const BRAND_NAME = "Dove";

const products: ProductScorecard[] = [

  /* -------------------------------------------------
     1. Body Love Supple Bounce Body Cream
     Source: incidecoder.com (verified June 2026)
     Nykaa: ~₹525
  ------------------------------------------------- */
  {
    productName: "Body Love Supple Bounce Body Cream",
    slug: "body-love-supple-bounce-body-cream",
    brand: BRAND_NAME,
    brandSlug: BRAND_SLUG,
    priceRange: "₹525",
    productType: "leave-on",
    concern: "Moisturisation, skin bounce, body firming feel",
    summary: "Dove Body Love Supple Bounce is a leave-on body cream from Dove's Body Love range, designed to deliver long-lasting moisture and a characteristic silicone-smooth, bouncy skin feel. The INCI is led by glycerin and a silicone system with petrolatum as a well-established occlusive, and includes Isomerized Linoleic Acid as a genuine functional active with published barrier support evidence. Reviews from Indian users consistently praise the rich texture and immediate skin feel, though some flag it as too heavy in summer months.",
    score: 70,
    scoreLabel: "Good",
    publicDecisionLabel: "Mostly credible with gaps",
    image: "https://incidecoder-content.storage.googleapis.com/bb001cc9-b280-4911-86f6-b0df8562aa85/products/dove-body-love-supple-bounce/dove-body-love-supple-bounce_front_photo_original.jpeg",
    pillars: [
      {
        name: "Public INCI Safety Screen",
        score: 25,
        max: 30,
        note: "No banned or prohibited substances were found across EU 1223/2009, India CR 2020, Health Canada Hotlist, MFDS Korea, US FDA 21 CFR, or ECHA SVHC. No parabens, no formaldehyde releasers, no endocrine disruptors with confirmed flags. The formula carries synthetic fragrance (Parfum) in a leave-on product, which is the primary safety note here. A fragrance complex is a hidden mix of potentially hundreds of undisclosed chemicals, and for a leave-on body cream used daily, this represents an allergen exposure that cannot be fully mapped from the INCI alone. To the brand's credit, 8 EU Annex III fragrance allergens are individually named in the INCI: Alpha-Isomethyl Ionone, Benzyl Alcohol, Benzyl Benzoate, Citronellol, Geraniol, Hexyl Cinnamal, Limonene, and Linalool. That individual disclosure is a transparency positive and does not create an additional concern beyond the fragrance itself. Geraniol, Citronellol, and Hexyl Cinnamal are recognised contact sensitisers worth noting for people with fragrance sensitivity. Petrolatum is a cosmetic-grade occlusive with an established safety record at EU-compliant quality levels. PEG-100 Stearate is a PEG-derived emulsifier that is generally well-tolerated; occasional sensitivity is possible in people with a compromised skin barrier. No drying alcohols are present.",
      },
      {
        name: "Formula Logic Inference",
        score: 22,
        max: 25,
        note: "Glycerin appears early in the formula, consistent with a dominant humectant concentration. The silicone system, with both Dimethicone and Dimethiconol present, is coherent and well-suited to a body cream targeting a smooth, bouncy skin feel. Petrolatum is among the most evidence-supported occlusives in cosmetic science and its placement is appropriate. Isomerized Linoleic Acid is a genuine functional active: linoleic acid isomers have published evidence supporting ceramide synthesis in the epidermis, which translates to measurable barrier function improvement. Camellia Sinensis Leaf Extract contributes antioxidant catechins, including EGCG. Helianthus Annuus Sunflower Seed Oil adds linoleic acid as a barrier-supportive emollient. The preservation system is identifiable: phenoxyethanol and caprylyl glycol together are a recognised and commonly used strategy for this product type. No pH-dependent actives requiring pH disclosure are present in this formula, so the absence of a published pH does not create a scoring gap here. The formula logic is coherent overall, with no active compatibility conflicts or ingredient contradictions visible from the public INCI.",
      },
      {
        name: "Public Claim Support",
        score: 13,
        max: 25,
        note: "Three key claims are assessed here. The 'Supple Bounce' name and associated claim is a sensory descriptor. The bounce feel is generated by the silicone system, which is real and verifiable from the INCI. However 'bounce' as an elasticity or structural skin claim is not backed by any publicly visible clinical evidence for this specific formula. The claim sits as marketing language with a functional INCI basis but no finished-product clinical proof. The '48-hour moisturisation' claim is a specific duration claim requiring a finished-product moisturisation study. No such study is publicly cited by Dove for this product, so this claim sits as mentioned-only without independent visible test data. The 'No drying alcohols' claim is verifiable directly from the INCI, which confirms no denatured alcohol, SD Alcohol, or similar short-chain alcohols are present. This claim is publicly supported. Overall, the stronger efficacy claims lack visible test reports, pulling this pillar down substantially.",
      },
      {
        name: "Test Result Transparency",
        score: 7,
        max: 15,
        evidenceGrade: "C",
        note: "Dove does not publish lab test reports, ISO method citations, or clinical study data for this product on any publicly accessible page. The INCI itself is available through InciDecoder rather than on Dove's own brand product page, which limits INCI transparency credit. No preservation efficacy test result is publicly accessible. No finished-product moisturisation study methodology or outcome is cited. No dermatologist test report with lab name, sample size, method, and result has been found in public sources. Dove uses 'dermatologist tested' language as a brand-level badge, but without a linked study that meets the standard criteria of method, sample size, result, and date, this sits as a badge without visible backing. The INCI being publicly available through third-party sources provides some baseline, but the absence of any published supporting test documentation means a Grade C is the honest assessment.",
      },
      {
        name: "Consumer Clarity",
        score: 3,
        max: 5,
        note: "Basic use instructions are present: apply to skin after bathing. Frequency of use is implied by the daily-use positioning of the product. Minimal skin type guidance is offered, though the cream is broadly positioned for dry to normal skin. There is no proactive fragrance allergen risk disclosure despite the 8 named EU allergens in the INCI, which would be useful information for consumers with known fragrance sensitivities. No specific warnings about avoiding broken or sensitised skin are provided. The absence of proactive allergen risk communication and suitability caveats for fragrance-sensitive users accounts for the two points not scored here.",
      },
    ],
    globalScreen: {
      eu_1223_2009: "No obvious public red flag found",
      india_cr_2020: "No obvious public red flag found",
      health_canada_hotlist: "No obvious public red flag found",
      canada_nhpid: "Not triggered",
      tga_australia: "Not triggered",
      us_fda_21cfr: "No obvious public red flag found",
      korea_mfds: "No obvious public red flag found",
      aicis_australia: "No obvious public red flag found",
      echa_svhc: "No obvious public red flag found",
      iarc: "No obvious public red flag found",
    },
    inciCompleteness: {
      status: "Marketplace only",
      flags: ["INCI sourced from InciDecoder, not from Dove's own brand product page"],
    },
    keyActives: [
      {
        name: "Glycerin",
        function: "Humectant that draws water into the skin. Listed high in the formula, consistent with a dominant working concentration.",
        concentrationConfidence: "Medium",
      },
      {
        name: "Dimethicone / Dimethiconol",
        function: "Silicone film-formers that create the characteristic smooth, bouncy skin feel and reduce transepidermal water loss.",
        concentrationConfidence: "Medium",
      },
      {
        name: "Petrolatum",
        function: "Highly effective occlusive with decades of evidence for skin barrier protection. Seals moisture into the skin.",
        concentrationConfidence: "Medium",
      },
      {
        name: "Isomerized Linoleic Acid",
        function: "Linoleic acid isomers with published evidence for ceramide synthesis support in the epidermis, improving skin barrier function.",
        concentrationConfidence: "Low",
      },
      {
        name: "Camellia Sinensis Leaf Extract",
        function: "Green tea extract providing EGCG catechins with antioxidant and mild anti-inflammatory properties.",
        concentrationConfidence: "Low",
      },
      {
        name: "Helianthus Annuus Sunflower Seed Oil",
        function: "Linoleic acid source serving as a barrier-supportive emollient.",
        concentrationConfidence: "Low",
      },
    ],
    ingredients: [
      { name: "Water",                                   note: "Solvent base.",                                                                                                                       flag: "ok"   },
      { name: "Glycerin",                                note: "Dominant humectant; appears well up in the ingredient list, consistent with a meaningful working concentration.",                     flag: "ok"   },
      { name: "Dimethicone",                             note: "Silicone that creates the characteristic Dove bounce texture and reduces transepidermal water loss.",                                 flag: "ok"   },
      { name: "Petrolatum",                              note: "Highly effective occlusive and skin barrier protectant with a well-established safety record. Petroleum-derived, EU-grade compliant.", flag: "ok"   },
      { name: "Stearic Acid",                            note: "Fatty acid emulsifier and emollient.",                                                                                               flag: "ok"   },
      { name: "Caprylic/Capric Triglyceride",            note: "Coconut-derived lightweight emollient.",                                                                                             flag: "ok"   },
      { name: "Glycol Stearate",                         note: "Emulsifier that gives the cream a slight pearlescent quality.",                                                                      flag: "ok"   },
      { name: "Stearamide AMP",                          note: "Fatty amide serving as an emollient and skin-conditioning agent.",                                                                   flag: "ok"   },
      { name: "Dimethiconol",                            note: "High-molecular-weight silicone contributing glide and film-formation.",                                                              flag: "ok"   },
      { name: "PEG-100 Stearate",                        note: "PEG-derived emulsifier. Generally well-tolerated. Occasional sensitivity is possible in people with a compromised skin barrier.",   flag: "info" },
      { name: "Caprylyl Glycol",                         note: "Humectant and preservative booster. Part of the identifiable preservation system alongside phenoxyethanol.",                        flag: "info" },
      { name: "Glyceryl Stearate",                       note: "Emulsifier.",                                                                                                                       flag: "ok"   },
      { name: "Phenoxyethanol",                          note: "Preservative within the standard 1% limit. Part of the identifiable preservation system.",                                          flag: "info" },
      { name: "Acrylates/C10-30 Alkyl Acrylate Crosspolymer", note: "Polymer thickener and texture modifier.",                                                                                     flag: "ok"   },
      { name: "Cetyl Alcohol",                           note: "Fatty alcohol used for texture and emulsion stabilisation. Not a drying alcohol.",                                                  flag: "ok"   },
      { name: "Sodium Hydroxide",                        note: "pH adjuster.",                                                                                                                      flag: "ok"   },
      { name: "Camellia Sinensis Leaf Extract",          note: "Green tea extract providing EGCG and other catechins with antioxidant and mild anti-inflammatory properties.",                      flag: "ok"   },
      { name: "Titanium Dioxide",                        note: "Opacifier giving the cream its white appearance. Not functioning as a sunscreen in this formula.",                                  flag: "ok"   },
      { name: "Carbomer",                                note: "Polymer thickener.",                                                                                                                flag: "ok"   },
      { name: "Isomerized Linoleic Acid",                note: "Linoleic acid isomers with published evidence for ceramide synthesis support and skin barrier improvement.",                        flag: "ok"   },
      { name: "Helianthus Annuus Sunflower Seed Oil",    note: "Linoleic acid source serving as a barrier-supportive emollient.",                                                                   flag: "ok"   },
      { name: "Fragrance",                               note: "Synthetic fragrance complex in a leave-on product. The full chemical composition is not disclosed. Eight EU Annex III allergens are individually named in the INCI, which is a transparency positive.", flag: "warn" },
      { name: "Alpha-Isomethyl Ionone",                  note: "EU Annex III declared fragrance allergen. Violet and woody scent character. Moderate sensitisation potential.",                     flag: "warn" },
      { name: "Benzyl Alcohol",                          note: "EU Annex III declared fragrance allergen. Also has mild preservative activity.",                                                     flag: "warn" },
      { name: "Benzyl Benzoate",                         note: "EU Annex III declared fragrance allergen.",                                                                                         flag: "warn" },
      { name: "Citronellol",                             note: "EU Annex III declared fragrance allergen with rose and citrus character. Recognised as a significant contact sensitiser.",          flag: "warn" },
      { name: "Geraniol",                                note: "EU Annex III declared fragrance allergen. One of the more commonly identified contact sensitisers in fragrance safety studies.",    flag: "warn" },
      { name: "Hexyl Cinnamal",                          note: "EU Annex III declared fragrance allergen. Frequently identified in fragrance contact dermatitis patch test studies.",               flag: "warn" },
      { name: "Limonene",                                note: "EU Annex III declared fragrance allergen. Citrus-derived. Oxidised limonene is a more potent sensitiser than the fresh form.",     flag: "warn" },
      { name: "Linalool",                                note: "EU Annex III declared fragrance allergen. Floral character. Oxidised linalool is a recognised sensitiser.",                        flag: "warn" },
    ],
    claimsCheck: [
      {
        claim: "Supple Bounce",
        evidenceStatus: "Mentioned only",
        decision: "Needs proof",
        note: "The silicone system in the INCI plausibly explains the bounce skin feel, but no finished-product clinical evidence for elasticity or structural skin improvement is publicly cited.",
      },
      {
        claim: "48-hour moisturisation",
        evidenceStatus: "Mentioned only",
        decision: "Needs proof",
        note: "This is a specific duration claim that requires a finished-product moisturisation study using a validated method; no such test or result has been found in publicly available sources.",
      },
      {
        claim: "No drying alcohols",
        evidenceStatus: "Evidence visible",
        decision: "Publicly supported",
        note: "The INCI confirms the absence of denatured alcohol, SD Alcohol, and similar short-chain drying alcohols. This claim is directly verifiable from the ingredient list.",
      },
    ],
    missingProof: [
      "No finished-product moisturisation study is publicly available. To support the 48-hour moisturisation claim, a corneometer-based or equivalent finished-product test result with methodology, sample size, and outcome would be needed.",
      "No clinical or consumer study supporting the 'Supple Bounce' positioning is publicly cited. Evidence specifically measuring skin elasticity or bounce before and after use on this formula would be required.",
      "INCI is available through InciDecoder but not on Dove's own brand product page. Publishing the full ingredient list on the official product page would improve INCI transparency.",
      "No preservative efficacy test result (ISO 11930) is publicly accessible. Given the water-based formula, a published challenge test result would confirm the preservation system is adequate.",
      "No proactive fragrance allergen risk disclosure is provided on product packaging or the brand website despite 8 named EU Annex III allergens being present in the formula.",
    ],
    pass_badges: ["INCI Verified", "No Drying Alcohols", "No Parabens"],
    warn_badges: ["Synthetic Fragrance", "Fragrance Allergens Present", "Claim Not Publicly Substantiated", "INCI Not on Brand Website"],
    info_badges: ["Isomerized Linoleic Acid is a genuine barrier-supportive active with ceramide synthesis evidence", "Preservative System Identified"],
    indiaContext: "Dove is one of India's most accessible body care brands, available across every pharmacy, supermarket, and online platform. The silicone-heavy Body Love Supple Bounce formula delivers a luxurious, instantly bouncy skin feel that performs well in marketing. The Petrolatum and Dimethicone combination is genuinely effective for barrier protection in dry, air-conditioned environments. However, 8 EU-listed fragrance allergens is a high allergen burden for Indian consumers, particularly given the prevalence of fragrance contact dermatitis in humid climates where skin absorption tends to be higher. The formula is also relatively occlusive and may feel heavy in peak Indian summer or in humid coastal cities. At approximately Rs.525, there are cleaner and lighter alternatives in the Indian market at a comparable price point.",
    cleanSheetNote: "This assessment is based only on publicly available INCI, claims, and test evidence. It is not a full Clean Sheet certification. Full certification requires confidential formula review, exact concentrations, supplier documentation, manufacturing records, packaging compatibility, preservative efficacy, stability, and complete claim validation.",
    analyzedAt: "2026-06-09",
    category: "Body Care",
    subCategory: "Body Cream",
    price: 525,
    sizeValue: 300,
    sizeUnit: "ml",
    pricePerUnit: 1.75,
    skinTypeTags: ["normal", "dry"],
    concernTags: ["Moisturisation", "Skin Bounce"],
    suitabilityTags: ["Normal Skin", "Dry Skin"],
    cautionTags: ["Contains Fragrance", "Multiple Fragrance Allergens"],
    routineSlot: "AM+PM",
    fragranceStatus: "synthetic",
    alcoholStatus: "free",
    certificationStatus: "not-certified",
    claimsMade: ["Supple bounce", "48-hour moisturisation", "Skin barrier support"],
    claimsVerified: ["No drying alcohols confirmed from INCI", "Moisturisation plausible from glycerin, petrolatum, and dimethicone", "Isomerized Linoleic Acid has ceramide synthesis evidence"],
    claimsNotVerified: ["'Supple bounce' sensory descriptor without clinical elasticity evidence", "48-hour moisturisation duration not supported by a publicly visible finished-product study"],
    availabilitySources: ["Nykaa", "Amazon India", "Supermarkets", "Pharmacies"],
  },

];

export const doveBrand: Brand = {
  name: BRAND_NAME,
  slug: BRAND_SLUG,
  logo: "https://incidecoder-content.storage.googleapis.com/bb001cc9-b280-4911-86f6-b0df8562aa85/products/dove-body-love-supple-bounce/dove-body-love-supple-bounce_front_photo_original.jpeg",
  tagline: "Real care for real beauty",
  description: "Dove is a Unilever personal care brand founded in the US in 1957, now sold in over 150 countries. In India, Dove is one of the most widely distributed body care brands with strong pharmacy, grocery, and e-commerce presence. The brand is known for its 1/4 moisturising cream positioning, Body Love campaign for body positivity, and accessible price point. Dove's parent company is Unilever, which operates globally including in markets where animal testing is required for import registration (e.g. China). Dove is not independently certified cruelty-free by Leaping Bunny or PETA.",
  founded: "1957",
  headquarters: "Unilever PLC, London, UK",
  website: "https://www.dove.com/in",
  instagramHandle: "@dove",
  nykaaUrl: "https://www.nykaa.com/brands/dove/c/1027",
  avgScore: Math.round(products.reduce((sum, p) => sum + p.score, 0) / products.length),
  verdict: "Dove Body Love Supple Bounce is a well-formulated, accessible moisturiser with a high-performing silicone and glycerin base. The Isomerized Linoleic Acid is a genuine barrier-supportive active. However the 8 EU-listed fragrance allergens and the absence of published test reports for key claims are notable gaps. For consumers prioritising cruelty-free or fragrance-free formulas, this product falls short. For everyone else, it is a functional and affordable daily moisturiser.",
  products,
};
